### ISSUE TITLE
Sentences are not in order

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel-chrome-extension#1]
It seems that the sentences output by extension are output in order of the score output by summarizer. However,  for more fluent text, top-k sentences should be output in their original order.

**Comment by husnusensoy** [comment]
@askarbozcan can you confirm that it is not the case for the web service also ?  @mccakir can you please confirm the bug

**Comment by mccakir** [comment]
I couldn't reproduce the issue. Could you provide example url that you face with it?

**Comment by askarbozcan** [comment]
The problem was in server code. Selected sentence indices were not sorted in ascending order.
Fixed in recent pull request on main repo.
